#debug: false

server:
    port: 8080

spring:
      datasource:
          name: test
          url: jdbc:mysql://39.108.55.167:3306/LinkShare?useSSL=true
          username: root
          password: 963852741wa
          # 使用druid数据源
          type: com.alibaba.druid.pool.DruidDataSource
          driver-class-name: com.mysql.jdbc.Driver
          druid:
            filters: stat,wall,log4j
            maxActive: 20
            initialSize: 1
            maxWait: 60000
            minIdle: 1
            timeBetweenEvictionRunsMillis: 60000
            minEvictableIdleTimeMillis: 300000
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            poolPreparedStatements: true
            maxOpenPreparedStatements: 20
